@startuml

interface Language {
    + detect(text: string): vector<Rule>
}

interface Rule {
    + correct(text: string&)
}

Language .> Rule

Language <|.. Russian
Language <|.. English

Rule <|.. KeepLetterE
Rule <|.. VowelAfterSizzling

@enduml